using Api.Application.Authentication;
using Api.Application.Extensions;
using Api.Application.Models;
using Api.Product.Billing.Models;
using Api.Product.Billing.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Api.Product.Billing;

/// <summary>
/// Provides invoice read endpoints for the authenticated tenant.
/// </summary>
/// <remarks>
/// These endpoints are admin-only and return invoices generated by the monthly billing process.
/// </remarks>
[ApiController]
[Route("v1/[controller]")]
[Authorize(Roles = nameof(AccountRoles.AdminUserRole))]
public class InvoiceController : ControllerBase
{
    private readonly IInvoiceService _invoiceService;

    public InvoiceController(IInvoiceService invoiceService)
    {
        _invoiceService = invoiceService;
    }

    /// <summary>
    /// Gets all invoices for the current tenant.
    /// </summary>
    /// <returns>A list of invoices ordered by billing period (newest first).</returns>
    /// <response code="200">Invoices retrieved successfully.</response>
    /// <response code="401">Authentication is required.</response>
    /// <response code="403">Admin role is required.</response>
    /// <response code="500">An unexpected error occurred while retrieving invoices.</response>
    [HttpGet]
    [ProducesResponseType(typeof(List<InvoiceModel>), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ApplicationProblemDetailsModel), StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(typeof(ApplicationProblemDetailsModel), StatusCodes.Status403Forbidden)]
    [ProducesResponseType(typeof(ApplicationProblemDetailsModel), StatusCodes.Status500InternalServerError)]
    public async Task<ActionResult<List<InvoiceModel>>> GetInvoices()
    {
        var result = await _invoiceService.GetInvoicesForTenantAsync();
        if (result.IsFailure)
        {
            var problem = result.ErrorModel.ToApplicationProblemDetails(HttpContext);
            return StatusCode(problem.Status ?? StatusCodes.Status400BadRequest, problem);
        }

        return Ok(result.GetValue);
    }

    /// <summary>
    /// Gets a single invoice by its identifier.
    /// </summary>
    /// <param name="invoiceId">Invoice identifier.</param>
    /// <returns>The requested invoice with line items.</returns>
    /// <response code="200">Invoice retrieved successfully.</response>
    /// <response code="401">Authentication is required.</response>
    /// <response code="403">Admin role is required.</response>
    /// <response code="404">Invoice was not found for the current tenant.</response>
    /// <response code="500">An unexpected error occurred while retrieving the invoice.</response>
    [HttpGet("{invoiceId:long}")]
    [ProducesResponseType(typeof(InvoiceModel), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ApplicationProblemDetailsModel), StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(typeof(ApplicationProblemDetailsModel), StatusCodes.Status403Forbidden)]
    [ProducesResponseType(typeof(ApplicationProblemDetailsModel), StatusCodes.Status404NotFound)]
    [ProducesResponseType(typeof(ApplicationProblemDetailsModel), StatusCodes.Status500InternalServerError)]
    public async Task<ActionResult<InvoiceModel>> GetInvoice(long invoiceId)
    {
        var result = await _invoiceService.GetInvoiceAsync(invoiceId);
        if (result.IsFailure)
        {
            var problem = result.ErrorModel.ToApplicationProblemDetails(HttpContext);
            return StatusCode(problem.Status ?? StatusCodes.Status400BadRequest, problem);
        }

        return Ok(result.GetValue);
    }
}
